"""
Strategy signal definitions.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum


class SignalAction(StrEnum):
    """Possible strategy decisions."""

    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"


@dataclass(frozen=True, slots=True)
class StrategySignal:
    """
    Decision generated by the strategy layer.

    The strategy only decides what should happen.
    Position sizing, risk limits and order execution are handled elsewhere.
    """

    symbol: str
    action: SignalAction

    score: float
    reason: str

    stop_loss_price: float | None = None
    take_profit_price: float | None = None